M48
; DRILL file KiCad 10.0.3 date 2026-08-23T20:33:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-23T20:33:36+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X94.6Y-45.2
X114.2Y-45.2
T2
X69.4Y-114.0
X69.4Y-131.6
X135.2Y-114.0
X135.2Y-131.6
M30
